env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/require-default-props: 0
  react/function-component-definition: 0
  react/jsx-filename-extension: 0
  import/extensions: 0
  import/no-unresolved: 0
  react/jsx-props-no-spreading: 0
  react/react-in-jsx-scope: 0
  import/prefer-default-export: 0
  react/prop-types: 0
  react/no-unescaped-entities: 0
  max-classes-per-file: 0
  no-use-before-define: 0
