# This is a basic workflow to help you get started with Actions

name: Build and deploy to IPFS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Runs a set of commands using the runners shell
      - name: publish to ipfs
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.PINATA_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.PINATA_SECRET }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: freecodecampdallas.com
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.test.freecodecampdallas.com
          CI: true
        run: npx ipfs-deploy -p pinata -d cloudflare -O .
